using System.Globalization;
using System.Text;
using EasyOcrSharp.Evaluation;
using EasyOcrSharp.Models;
using Xunit;

namespace EasyOcrSharp.Tests;

/// <summary>
/// Unit tests for <see cref="TextAccuracyMetrics"/> — CER / WER, the alignment breakdown, the
/// normalization options and the <see cref="OcrResult"/> convenience overloads. Every member under test
/// is a pure function over strings, so nothing here touches a model, the disk or the network.
/// </summary>
/// <remarks>
/// All non-ASCII fixtures are written as escape sequences so the expected code points survive whatever
/// encoding this file is stored in — an accented character that silently changes shape would turn a
/// grapheme-vs-code-unit assertion into a lie.
/// </remarks>
public class EvaluationMetricsTests
{
    // U+1F600 GRINNING FACE — a non-BMP scalar, i.e. one grapheme, one rune, two UTF-16 code units.
    private const string Emoji = "\U0001F600";

    // "e" + U+0301 COMBINING ACUTE ACCENT versus the precomposed U+00E9.
    private const string DecomposedEAcute = "é";
    private const string PrecomposedEAcute = "é";

    private const string Cjk = "日本語";          // "nihongo"
    private const string FullWidthDigits = "１２３"; // full-width 1 2 3
    private const string Nbsp = " ";

    // ---------------------------------------------------------------- helpers

    private static int GraphemeCount(string text) => Graphemes(text).Count;

    private static List<string> Graphemes(string text)
    {
        var elements = new List<string>();
        var enumerator = StringInfo.GetTextElementEnumerator(text);
        while (enumerator.MoveNext()) elements.Add(enumerator.GetTextElement());
        return elements;
    }

    private static string[] Tokens(string text)
        => text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);

    /// <summary>
    /// The textbook full-matrix Levenshtein distance. Deliberately the naive O(n*m) memory version so it
    /// shares no code (and no bugs) with the two-rolling-rows implementation under test.
    /// </summary>
    private static int NaiveLevenshtein<T>(IReadOnlyList<T> a, IReadOnlyList<T> b)
        where T : IEquatable<T>
    {
        var d = new int[a.Count + 1, b.Count + 1];
        for (int i = 0; i <= a.Count; i++) d[i, 0] = i;
        for (int j = 0; j <= b.Count; j++) d[0, j] = j;

        for (int i = 1; i <= a.Count; i++)
        {
            for (int j = 1; j <= b.Count; j++)
            {
                int cost = a[i - 1].Equals(b[j - 1]) ? 0 : 1;
                d[i, j] = Math.Min(Math.Min(d[i - 1, j] + 1, d[i, j - 1] + 1), d[i - 1, j - 1] + cost);
            }
        }

        return d[a.Count, b.Count];
    }

    /// <summary>
    /// A fixed set of small string pairs for the cross-check tests. Generated by a hand-rolled xorshift
    /// with a hard-coded seed rather than <see cref="Random"/>, so the corpus is byte-for-byte the same
    /// on every machine, every run and every framework version.
    /// </summary>
    private static IReadOnlyList<(string Reference, string Hypothesis)> DeterministicPairs()
    {
        const string alphabet = "abcx ";
        uint state = 0x2545F491u;

        uint Next()
        {
            state ^= state << 13;
            state ^= state >> 17;
            state ^= state << 5;
            return state;
        }

        string Make(int length)
        {
            var chars = new char[length];
            for (int i = 0; i < length; i++) chars[i] = alphabet[(int)(Next() % (uint)alphabet.Length)];
            return new string(chars);
        }

        var pairs = new List<(string, string)>(80);
        for (int i = 0; i < 80; i++)
        {
            pairs.Add((Make((int)(Next() % 12u)), Make((int)(Next() % 12u))));
        }
        return pairs;
    }

    private static OcrResult ResultWithText(string text) => new()
    {
        FullText = text,
        Lines = [new OcrLine { Text = text, Confidence = 0.9 }],
        Languages = ["en"],
    };

    private static TextComparisonOptions Unit(CharacterUnit unit) => new() { CharacterUnit = unit };

    // ---------------------------------------------------------------- hand-computed fixtures

    [Fact]
    public void Identical_strings_score_zero_at_both_levels()
    {
        const string text = "the quick brown fox";

        var report = TextAccuracyMetrics.Compare(text, text);

        Assert.Equal(0.0, report.CharacterErrorRate, 10);
        Assert.Equal(0.0, report.WordErrorRate, 10);
        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate(text, text), 10);
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate(text, text), 10);
        Assert.Equal(new ErrorCounts(19, 0, 0, 0), report.Characters);
        Assert.Equal(new ErrorCounts(4, 0, 0, 0), report.Words);
        Assert.Equal(1.0, report.Characters.Accuracy, 10);
    }

    [Fact]
    public void A_single_substitution_costs_one_error_over_the_reference_length()
    {
        var counts = TextAccuracyMetrics.Compare("kitten", "sitten").Characters;

        Assert.Equal(new ErrorCounts(5, 1, 0, 0), counts);
        Assert.Equal(1.0 / 6, counts.ErrorRate, 10);
        Assert.Equal(1.0 / 6, TextAccuracyMetrics.CharacterErrorRate("kitten", "sitten"), 10);
    }

    [Fact]
    public void A_single_insertion_costs_one_error_over_the_reference_length()
    {
        // "cat" -> "cart": the hypothesis added an 'r' the ground truth does not have.
        var counts = TextAccuracyMetrics.Compare("cat", "cart").Characters;

        Assert.Equal(new ErrorCounts(3, 0, 1, 0), counts);
        Assert.Equal(3, counts.ReferenceLength);
        Assert.Equal(4, counts.HypothesisLength);
        Assert.Equal(1.0 / 3, counts.ErrorRate, 10);
    }

    [Fact]
    public void A_single_deletion_costs_one_error_over_the_reference_length()
    {
        // "cart" -> "cat": the recognizer dropped the 'r'.
        var counts = TextAccuracyMetrics.Compare("cart", "cat").Characters;

        Assert.Equal(new ErrorCounts(3, 0, 0, 1), counts);
        Assert.Equal(4, counts.ReferenceLength);
        Assert.Equal(3, counts.HypothesisLength);
        Assert.Equal(0.25, counts.ErrorRate, 10);
    }

    [Fact]
    public void A_completely_different_string_of_the_same_length_scores_one()
    {
        var counts = TextAccuracyMetrics.Compare("abc", "xyz").Characters;

        Assert.Equal(new ErrorCounts(0, 3, 0, 0), counts);
        Assert.Equal(1.0, counts.ErrorRate, 10);
        Assert.Equal(0.0, counts.Accuracy, 10);
    }

    [Fact]
    public void The_textbook_kitten_sitting_distance_is_three()
    {
        Assert.Equal(3, TextAccuracyMetrics.LevenshteinDistance("kitten", "sitting"));
        Assert.Equal(3, TextAccuracyMetrics.Compare("kitten", "sitting").Characters.TotalErrors);
        Assert.Equal(0.5, TextAccuracyMetrics.CharacterErrorRate("kitten", "sitting"), 10);
    }

    [Fact]
    public void A_hypothesis_far_longer_than_the_reference_can_exceed_a_rate_of_one()
    {
        var counts = TextAccuracyMetrics.Compare("a", "abcdefgh").Characters;

        Assert.Equal(new ErrorCounts(1, 0, 7, 0), counts);
        Assert.Equal(7.0, counts.ErrorRate, 10);
        // Accuracy is clamped so a hallucinating recognizer reads as 0%, not -600%.
        Assert.Equal(0.0, counts.Accuracy, 10);
    }

    [Fact]
    public void An_alignment_that_has_to_swap_the_two_sequences_reports_insertions_not_deletions()
    {
        // The hypothesis is the longer sequence, so the implementation swaps the rolling-row dimensions
        // internally; the edit labels must be swapped back on the way out.
        var counts = TextAccuracyMetrics.Compare("xy", "abcxyz").Characters;

        Assert.Equal(new ErrorCounts(2, 0, 4, 0), counts);
        Assert.Equal(2, counts.ReferenceLength);
        Assert.Equal(6, counts.HypothesisLength);
        Assert.Equal(2.0, counts.ErrorRate, 10);
    }

    [Fact]
    public void A_one_letter_slip_costs_a_whole_word_but_only_two_characters()
    {
        // "quick" -> "quikc" is one transposed pair: two character edits, one ruined word out of four.
        var report = TextAccuracyMetrics.Compare("the quick brown fox", "the quikc brown fox");

        Assert.Equal(2.0 / 19, report.CharacterErrorRate, 10);
        Assert.Equal(0.25, report.WordErrorRate, 10);
        Assert.Equal(new ErrorCounts(3, 1, 0, 0), report.Words);
    }

    // ---------------------------------------------------------------- empty input

    [Fact]
    public void Two_empty_strings_are_a_perfect_match()
    {
        var report = TextAccuracyMetrics.Compare(string.Empty, string.Empty);

        Assert.Equal(ErrorCounts.Empty, report.Characters);
        Assert.Equal(ErrorCounts.Empty, report.Words);
        Assert.Equal(0.0, report.CharacterErrorRate, 10);
        Assert.Equal(0.0, report.WordErrorRate, 10);
    }

    [Fact]
    public void An_empty_reference_scores_one_against_any_non_empty_hypothesis()
    {
        // Documented behaviour: the divide-by-zero case is defined as 0.0 for an empty hypothesis and
        // 1.0 for anything else, rather than NaN or infinity.
        var counts = TextAccuracyMetrics.Compare(string.Empty, "hello").Characters;

        Assert.Equal(0, counts.ReferenceLength);
        Assert.Equal(5, counts.HypothesisLength);
        Assert.Equal(5, counts.Insertions);
        Assert.Equal(1.0, counts.ErrorRate, 10);
        Assert.Equal(1.0, TextAccuracyMetrics.CharacterErrorRate(string.Empty, "hello"), 10);
        Assert.Equal(1.0, TextAccuracyMetrics.WordErrorRate(string.Empty, "hello"), 10);
    }

    [Fact]
    public void An_empty_hypothesis_scores_one_against_any_reference()
    {
        var counts = TextAccuracyMetrics.Compare("hello", string.Empty).Characters;

        Assert.Equal(new ErrorCounts(0, 0, 0, 5), counts);
        Assert.Equal(1.0, counts.ErrorRate, 10);
        Assert.Equal(0.0, counts.Accuracy, 10);
    }

    [Fact]
    public void A_whitespace_only_reference_has_characters_to_lose_but_no_words()
    {
        // The two levels legitimately disagree here: three characters were deleted, but neither side
        // tokenizes to a single word, so WER falls into the "empty reference, empty hypothesis" case.
        var report = TextAccuracyMetrics.Compare(" \t\n", string.Empty);

        Assert.Equal(1.0, report.CharacterErrorRate, 10);
        Assert.Equal(3, report.Characters.Deletions);
        Assert.Equal(ErrorCounts.Empty, report.Words);
        Assert.Equal(0.0, report.WordErrorRate, 10);
    }

    [Fact]
    public void The_empty_error_counts_are_all_zero_and_score_as_perfect()
    {
        Assert.Equal(0, ErrorCounts.Empty.Hits);
        Assert.Equal(0, ErrorCounts.Empty.TotalErrors);
        Assert.Equal(0, ErrorCounts.Empty.ReferenceLength);
        Assert.Equal(0, ErrorCounts.Empty.HypothesisLength);
        Assert.Equal(0.0, ErrorCounts.Empty.ErrorRate, 10);
        Assert.Equal(1.0, ErrorCounts.Empty.Accuracy, 10);
    }

    [Fact]
    public void Levenshtein_distance_of_empty_spans_is_the_other_length()
    {
        Assert.Equal(0, TextAccuracyMetrics.LevenshteinDistance(string.Empty, string.Empty));
        Assert.Equal(4, TextAccuracyMetrics.LevenshteinDistance(string.Empty, "abcd"));
        Assert.Equal(4, TextAccuracyMetrics.LevenshteinDistance("abcd", string.Empty));
    }

    // ---------------------------------------------------------------- Unicode

    [Fact]
    public void An_emoji_is_one_grapheme_one_rune_and_two_code_units()
    {
        string reference = "a" + Emoji + "b";

        Assert.Equal(1.0 / 3, TextAccuracyMetrics.CharacterErrorRate(reference, "ab", Unit(CharacterUnit.Grapheme)), 10);
        Assert.Equal(1.0 / 3, TextAccuracyMetrics.CharacterErrorRate(reference, "ab", Unit(CharacterUnit.Rune)), 10);
        // The surrogate pair counts twice here — the documented reason Utf16CodeUnit exists only to
        // reproduce older benchmarks.
        Assert.Equal(0.5, TextAccuracyMetrics.CharacterErrorRate(reference, "ab", Unit(CharacterUnit.Utf16CodeUnit)), 10);
    }

    [Fact]
    public void A_combining_mark_belongs_to_its_base_grapheme_but_is_a_rune_of_its_own()
    {
        Assert.Equal(1.0, TextAccuracyMetrics.CharacterErrorRate(DecomposedEAcute, "e", Unit(CharacterUnit.Grapheme)), 10);
        Assert.Equal(0.5, TextAccuracyMetrics.CharacterErrorRate(DecomposedEAcute, "e", Unit(CharacterUnit.Rune)), 10);
        Assert.Equal(0.5, TextAccuracyMetrics.CharacterErrorRate(DecomposedEAcute, "e", Unit(CharacterUnit.Utf16CodeUnit)), 10);
    }

    [Fact]
    public void An_accented_word_scores_the_same_whether_the_accent_is_composed_or_not()
    {
        // Grapheme counting is what makes these two spellings of "cafe" score identically without any
        // Unicode normalization being switched on.
        Assert.Equal(0.25, TextAccuracyMetrics.CharacterErrorRate("caf" + PrecomposedEAcute, "cafe"), 10);
        Assert.Equal(0.25, TextAccuracyMetrics.CharacterErrorRate("caf" + DecomposedEAcute, "cafe"), 10);

        // Counting UTF-16 units instead makes the decomposed form look longer, and the rate changes.
        Assert.Equal(
            0.2,
            TextAccuracyMetrics.CharacterErrorRate("caf" + DecomposedEAcute, "cafe", Unit(CharacterUnit.Utf16CodeUnit)),
            10);
    }

    [Fact]
    public void Cjk_characters_count_one_each_in_every_unit()
    {
        string hypothesis = Cjk[..2];

        Assert.Equal(1.0 / 3, TextAccuracyMetrics.CharacterErrorRate(Cjk, hypothesis, Unit(CharacterUnit.Grapheme)), 10);
        Assert.Equal(1.0 / 3, TextAccuracyMetrics.CharacterErrorRate(Cjk, hypothesis, Unit(CharacterUnit.Rune)), 10);
        Assert.Equal(1.0 / 3, TextAccuracyMetrics.CharacterErrorRate(Cjk, hypothesis, Unit(CharacterUnit.Utf16CodeUnit)), 10);
    }

    [Fact]
    public void Graphemes_are_the_default_character_unit()
    {
        Assert.Equal(CharacterUnit.Grapheme, TextComparisonOptions.Default.CharacterUnit);

        string reference = "a" + Emoji + "b";
        Assert.Equal(
            TextAccuracyMetrics.CharacterErrorRate(reference, "ab", Unit(CharacterUnit.Grapheme)),
            TextAccuracyMetrics.CharacterErrorRate(reference, "ab"),
            10);
        // Passing null options must behave exactly like passing Default.
        Assert.Equal(
            TextAccuracyMetrics.CharacterErrorRate(reference, "ab", TextComparisonOptions.Default),
            TextAccuracyMetrics.CharacterErrorRate(reference, "ab", options: null),
            10);
    }

    [Theory]
    [InlineData(CharacterUnit.Grapheme)]
    [InlineData(CharacterUnit.Rune)]
    [InlineData(CharacterUnit.Utf16CodeUnit)]
    public void The_character_unit_never_changes_the_word_level_score(CharacterUnit unit)
    {
        string reference = "smile " + Emoji + " now";

        Assert.Equal(1.0 / 3, TextAccuracyMetrics.WordErrorRate(reference, "smile x now", Unit(unit)), 10);
    }

    [Fact]
    public void Unpaired_surrogates_are_compared_as_they_are_rather_than_throwing()
    {
        // string.Normalize rejects a lone surrogate; the metric swallows that and compares the raw text.
        const string malformed = "a\ud800b";
        var options = new TextComparisonOptions { UnicodeNormalization = NormalizationForm.FormC };

        Assert.Equal(malformed, TextAccuracyMetrics.Normalize(malformed, options));
        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate(malformed, malformed, options), 10);
        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate(malformed, malformed), 10);
    }

    [Fact]
    public void An_unpaired_surrogate_becomes_a_replacement_character_when_counting_runes()
    {
        // Rune enumeration cannot represent a lone surrogate, so it surfaces as U+FFFD — which still
        // compares equal to the same malformed input, and unequal to the well-formed neighbour.
        const string malformed = "a\ud800b";

        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate(malformed, malformed, Unit(CharacterUnit.Rune)), 10);
        Assert.Equal(1.0 / 3, TextAccuracyMetrics.CharacterErrorRate(malformed, "ab", Unit(CharacterUnit.Rune)), 10);
    }

    // ---------------------------------------------------------------- breakdown consistency

    [Theory]
    [InlineData("", "")]
    [InlineData("", "hello world")]
    [InlineData("hello world", "")]
    [InlineData("the quick brown fox", "the quick brown fox")]
    [InlineData("the quick brown fox", "teh quikc brwon fox jumps")]
    [InlineData("one", "one two three four five")]
    [InlineData("a b c d e", "a")]
    [InlineData("café naïve", "cafe naive")]
    [InlineData("日本語 テスト", "日本語")]
    [InlineData("smile \U0001F600 now", "smile now")]
    public void The_breakdown_is_internally_consistent_with_the_rates_and_the_input_lengths(
        string reference,
        string hypothesis)
    {
        var report = TextAccuracyMetrics.Compare(reference, hypothesis);

        AssertConsistent(report.Characters, GraphemeCount(reference), GraphemeCount(hypothesis));
        AssertConsistent(report.Words, Tokens(reference).Length, Tokens(hypothesis).Length);

        Assert.Equal(report.Characters.ErrorRate, report.CharacterErrorRate, 10);
        Assert.Equal(report.Words.ErrorRate, report.WordErrorRate, 10);

        // The rates the shorthand entry points return must be the same numbers the report carries.
        Assert.Equal(report.CharacterErrorRate, TextAccuracyMetrics.CharacterErrorRate(reference, hypothesis), 10);
        Assert.Equal(report.WordErrorRate, TextAccuracyMetrics.WordErrorRate(reference, hypothesis), 10);

        // ...and the totals must equal a minimal edit distance computed the naive way.
        Assert.Equal(NaiveLevenshtein(Graphemes(reference), Graphemes(hypothesis)), report.Characters.TotalErrors);
        Assert.Equal(NaiveLevenshtein(Tokens(reference), Tokens(hypothesis)), report.Words.TotalErrors);
    }

    private static void AssertConsistent(ErrorCounts counts, int referenceLength, int hypothesisLength)
    {
        Assert.Equal(referenceLength, counts.ReferenceLength);
        Assert.Equal(hypothesisLength, counts.HypothesisLength);
        Assert.Equal(referenceLength, counts.Hits + counts.Substitutions + counts.Deletions);
        Assert.Equal(hypothesisLength, counts.Hits + counts.Substitutions + counts.Insertions);
        Assert.Equal(counts.Substitutions + counts.Insertions + counts.Deletions, counts.TotalErrors);

        // Every edit is accounted for: the surplus of insertions over deletions is exactly the length gap.
        Assert.Equal(hypothesisLength - referenceLength, counts.Insertions - counts.Deletions);

        Assert.True(counts.Hits >= 0 && counts.Substitutions >= 0 && counts.Insertions >= 0 && counts.Deletions >= 0);

        double expectedRate = referenceLength == 0
            ? (counts.TotalErrors == 0 ? 0.0 : 1.0)
            : (double)counts.TotalErrors / referenceLength;
        Assert.Equal(expectedRate, counts.ErrorRate, 10);
        Assert.Equal(Math.Clamp(1.0 - expectedRate, 0.0, 1.0), counts.Accuracy, 10);
        Assert.InRange(counts.Accuracy, 0.0, 1.0);
    }

    [Fact]
    public void Error_counts_are_an_immutable_value_with_structural_equality()
    {
        var counts = new ErrorCounts(3, 1, 2, 0);
        var changed = counts with { Insertions = 5 };

        Assert.Equal(new ErrorCounts(3, 1, 2, 0), counts);
        Assert.Equal(2, counts.Insertions);
        Assert.Equal(5, changed.Insertions);
        Assert.NotEqual(counts, changed);
    }

    // ---------------------------------------------------------------- normalization options

    [Fact]
    public void Every_normalization_step_is_off_by_default()
    {
        var options = TextComparisonOptions.Default;

        Assert.False(options.IgnoreCase);
        Assert.False(options.CollapseWhitespace);
        Assert.False(options.StripPunctuation);
        Assert.False(options.UnicodeNormalization.HasValue);
        Assert.Equal(CharacterUnit.Grapheme, options.CharacterUnit);
        Assert.Equal(25_000_000L, options.MaxComparisonCells);

        // A freshly constructed instance must match the shared Default.
        Assert.Equal(options, new TextComparisonOptions());
    }

    [Fact]
    public void Normalizing_with_the_default_options_returns_the_text_untouched()
    {
        const string text = "  Mixed CASE, punctuation!  " + " ";

        Assert.Same(text, TextAccuracyMetrics.Normalize(text));
        Assert.Same(text, TextAccuracyMetrics.Normalize(text, TextComparisonOptions.Default));
    }

    [Fact]
    public void Case_folding_changes_the_score_only_when_it_is_enabled()
    {
        Assert.Equal(0.2, TextAccuracyMetrics.CharacterErrorRate("Hello", "hello"), 10);
        Assert.Equal(
            0.0,
            TextAccuracyMetrics.CharacterErrorRate("Hello", "hello", new TextComparisonOptions { IgnoreCase = true }),
            10);
        Assert.Equal("hello world", TextAccuracyMetrics.Normalize("Hello World", new TextComparisonOptions { IgnoreCase = true }));
    }

    [Fact]
    public void Whitespace_collapsing_changes_the_score_only_when_it_is_enabled()
    {
        Assert.Equal(0.25, TextAccuracyMetrics.CharacterErrorRate("a  b", "a b"), 10);

        var options = new TextComparisonOptions { CollapseWhitespace = true };
        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate("a  b", "a b", options), 10);
        Assert.Equal("one two three", TextAccuracyMetrics.Normalize("  one \t two \r\n three  ", options));
    }

    [Fact]
    public void Whitespace_collapsing_makes_a_different_line_wrap_free_of_charge()
    {
        const string reference = "one two three";
        const string hypothesis = "one\ttwo\nthree";

        // Tabs and newlines are real character errors until collapsing is turned on...
        Assert.Equal(2.0 / 13, TextAccuracyMetrics.CharacterErrorRate(reference, hypothesis), 10);
        Assert.Equal(
            0.0,
            TextAccuracyMetrics.CharacterErrorRate(reference, hypothesis, new TextComparisonOptions { CollapseWhitespace = true }),
            10);
        // ...but the word level never saw them as anything but delimiters.
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate(reference, hypothesis), 10);
    }

    [Fact]
    public void Punctuation_stripping_changes_the_score_only_when_it_is_enabled()
    {
        const string reference = "Hello, world!";
        const string hypothesis = "Hello world";

        Assert.Equal(2.0 / 13, TextAccuracyMetrics.CharacterErrorRate(reference, hypothesis), 10);
        Assert.Equal(
            0.0,
            TextAccuracyMetrics.CharacterErrorRate(reference, hypothesis, new TextComparisonOptions { StripPunctuation = true }),
            10);
    }

    [Fact]
    public void Punctuation_stripping_removes_every_unicode_punctuation_category()
    {
        var options = new TextComparisonOptions { StripPunctuation = true };

        // Pc, Pd, Ps/Pe, Pi/Pf, Po — including the non-ASCII ones.
        Assert.Equal("ab", TextAccuracyMetrics.Normalize("a_b", options));
        Assert.Equal("ab", TextAccuracyMetrics.Normalize("a—b", options));
        Assert.Equal("ab", TextAccuracyMetrics.Normalize("a(b)", options));
        Assert.Equal("ab", TextAccuracyMetrics.Normalize("a«b»", options));
        Assert.Equal("ab", TextAccuracyMetrics.Normalize("a、b", options));
    }

    [Fact]
    public void Punctuation_stripping_keeps_currency_and_maths_symbols()
    {
        var options = new TextComparisonOptions { StripPunctuation = true };

        // char.IsPunctuation excludes the Sc/Sm categories, so a mangled amount still counts as an error.
        Assert.Equal("$5 + 3 = 8 €2", TextAccuracyMetrics.Normalize("$5 + 3 = 8 €2", options));
        Assert.Equal(1.0 / 2, TextAccuracyMetrics.CharacterErrorRate("$5", "5", options), 10);
    }

    [Fact]
    public void Punctuation_stripping_also_removes_the_percent_sign()
    {
        // Recorded as the shipped behaviour: '%' is Unicode category Po, so char.IsPunctuation reports it
        // and it is dropped, even though the XML documentation lists it as a symbol that survives.
        var options = new TextComparisonOptions { StripPunctuation = true };

        Assert.Equal("100", TextAccuracyMetrics.Normalize("100%", options));
        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate("100%", "100", options), 10);
    }

    [Fact]
    public void Unicode_normalization_changes_the_score_only_when_it_is_enabled()
    {
        // Precomposed against decomposed: one grapheme each, but not the same grapheme.
        Assert.Equal(1.0, TextAccuracyMetrics.CharacterErrorRate(PrecomposedEAcute, DecomposedEAcute), 10);
        Assert.Equal(
            0.0,
            TextAccuracyMetrics.CharacterErrorRate(
                PrecomposedEAcute,
                DecomposedEAcute,
                new TextComparisonOptions { UnicodeNormalization = NormalizationForm.FormC }),
            10);
        Assert.Equal(
            0.0,
            TextAccuracyMetrics.CharacterErrorRate(
                PrecomposedEAcute,
                DecomposedEAcute,
                new TextComparisonOptions { UnicodeNormalization = NormalizationForm.FormD }),
            10);
    }

    [Fact]
    public void Compatibility_normalization_folds_full_width_digits_onto_ascii()
    {
        var kc = new TextComparisonOptions { UnicodeNormalization = NormalizationForm.FormKC };

        Assert.Equal("123", TextAccuracyMetrics.Normalize(FullWidthDigits, kc));
        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate("123", FullWidthDigits, kc), 10);

        // Canonical composition alone does not fold compatibility variants.
        Assert.Equal(
            1.0,
            TextAccuracyMetrics.CharacterErrorRate(
                "123",
                FullWidthDigits,
                new TextComparisonOptions { UnicodeNormalization = NormalizationForm.FormC }),
            10);
    }

    [Fact]
    public void Normalization_steps_run_in_a_fixed_order_so_combinations_do_not_interact()
    {
        // Punctuation is stripped before whitespace is collapsed, so removing the dash cannot leave a
        // double space behind.
        var options = new TextComparisonOptions { StripPunctuation = true, CollapseWhitespace = true };

        Assert.Equal("a b", TextAccuracyMetrics.Normalize("a - b", options));
        Assert.Equal("a b", TextAccuracyMetrics.Normalize("  a  ,  b  ", options));
    }

    [Fact]
    public void A_non_breaking_space_is_whitespace_for_both_collapsing_and_tokenization()
    {
        string text = "a" + Nbsp + "b";

        Assert.Equal("a b", TextAccuracyMetrics.Normalize(text, new TextComparisonOptions { CollapseWhitespace = true }));
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate("a b", text), 10);
    }

    [Fact]
    public void The_relaxed_preset_enables_exactly_the_four_forgiving_steps()
    {
        var relaxed = TextComparisonOptions.Relaxed;

        Assert.True(relaxed.IgnoreCase);
        Assert.True(relaxed.CollapseWhitespace);
        Assert.True(relaxed.StripPunctuation);
        Assert.Equal(NormalizationForm.FormKC, relaxed.UnicodeNormalization);
        Assert.Equal(CharacterUnit.Grapheme, relaxed.CharacterUnit);

        Assert.Equal("hello world", TextAccuracyMetrics.Normalize("  Hello,  WORLD!  ", relaxed));
        Assert.Equal(0.0, TextAccuracyMetrics.CharacterErrorRate("Hello,  WORLD!", "hello world", relaxed), 10);
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate("Hello,  WORLD!", "hello world", relaxed), 10);
    }

    [Fact]
    public void The_shared_option_presets_are_singletons_that_a_with_expression_cannot_mutate()
    {
        Assert.Same(TextComparisonOptions.Default, TextComparisonOptions.Default);
        Assert.Same(TextComparisonOptions.Relaxed, TextComparisonOptions.Relaxed);

        var derived = TextComparisonOptions.Default with { IgnoreCase = true, CharacterUnit = CharacterUnit.Rune };

        Assert.True(derived.IgnoreCase);
        Assert.Equal(CharacterUnit.Rune, derived.CharacterUnit);
        Assert.False(TextComparisonOptions.Default.IgnoreCase);
        Assert.Equal(CharacterUnit.Grapheme, TextComparisonOptions.Default.CharacterUnit);
        Assert.NotSame(TextComparisonOptions.Default, derived);
    }

    // ---------------------------------------------------------------- guard rails

    [Fact]
    public void A_comparison_larger_than_the_cell_budget_throws_instead_of_hanging()
    {
        var options = new TextComparisonOptions { MaxComparisonCells = 16 };

        var error = Assert.Throws<ArgumentException>(
            () => { _ = TextAccuracyMetrics.CharacterErrorRate("abcdefgh", "stuvwxyz", options); });

        Assert.Contains("MaxComparisonCells", error.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Identical_text_never_touches_the_cell_budget_because_the_whole_table_is_trimmed_away()
    {
        string text = string.Concat(Enumerable.Repeat("the quick brown fox ", 40));
        var options = new TextComparisonOptions { MaxComparisonCells = 1 };

        var report = TextAccuracyMetrics.Compare(text, text, options);

        Assert.Equal(0.0, report.CharacterErrorRate, 10);
        Assert.Equal(0.0, report.WordErrorRate, 10);
    }

    [Fact]
    public void The_cell_budget_is_measured_after_the_common_prefix_and_suffix_are_trimmed()
    {
        // 100 characters differing in exactly one position trims down to a 2x2 table, so a budget of four
        // cells is enough and a budget of three is not.
        string reference = new('x', 100);
        string hypothesis = reference[..50] + "y" + reference[51..];

        Assert.Equal(
            0.01,
            TextAccuracyMetrics.CharacterErrorRate(reference, hypothesis, new TextComparisonOptions { MaxComparisonCells = 4 }),
            10);
        Assert.Throws<ArgumentException>(
            () => { _ = TextAccuracyMetrics.CharacterErrorRate(reference, hypothesis, new TextComparisonOptions { MaxComparisonCells = 3 }); });
    }

    [Fact]
    public void Null_arguments_are_rejected()
    {
        // Typed rather than a bare null literal: the string and OcrResult overloads would both accept it.
        string missingText = null!;

        Assert.Throws<ArgumentNullException>(() => { _ = TextAccuracyMetrics.Compare(missingText, "a"); });
        Assert.Throws<ArgumentNullException>(() => { _ = TextAccuracyMetrics.Compare("a", missingText); });
        Assert.Throws<ArgumentNullException>(() => { _ = TextAccuracyMetrics.CharacterErrorRate(missingText, "a"); });
        Assert.Throws<ArgumentNullException>(() => { _ = TextAccuracyMetrics.CharacterErrorRate("a", missingText); });
        Assert.Throws<ArgumentNullException>(() => { _ = TextAccuracyMetrics.WordErrorRate(missingText, "a"); });
        Assert.Throws<ArgumentNullException>(() => { _ = TextAccuracyMetrics.WordErrorRate("a", missingText); });
        Assert.Throws<ArgumentNullException>(() => { _ = TextAccuracyMetrics.Normalize(missingText); });
    }

    [Fact]
    public void Null_ocr_results_and_null_expected_text_are_rejected()
    {
        OcrResult missing = null!;
        var present = ResultWithText("a");

        Assert.Throws<ArgumentNullException>(() => { _ = missing.CharacterErrorRate("a"); });
        Assert.Throws<ArgumentNullException>(() => { _ = missing.WordErrorRate("a"); });
        Assert.Throws<ArgumentNullException>(() => { _ = missing.Compare("a"); });
        Assert.Throws<ArgumentNullException>(() => { _ = present.CharacterErrorRate(null!); });
        Assert.Throws<ArgumentNullException>(() => { _ = present.WordErrorRate(null!); });
        Assert.Throws<ArgumentNullException>(() => { _ = present.Compare(null!); });
    }

    // ---------------------------------------------------------------- OcrResult overloads

    [Theory]
    [InlineData("the quick brown fox", "the quick brown fox")]
    [InlineData("the quick brown fox", "the quikc brown fox jumped")]
    [InlineData("hello", "")]
    [InlineData("", "hello")]
    [InlineData("café", "cafe")]
    public void The_result_overloads_agree_with_the_equivalent_raw_string_calls(string expected, string recognized)
    {
        var result = ResultWithText(recognized);

        Assert.Equal(TextAccuracyMetrics.CharacterErrorRate(expected, recognized), result.CharacterErrorRate(expected), 10);
        Assert.Equal(TextAccuracyMetrics.WordErrorRate(expected, recognized), result.WordErrorRate(expected), 10);
        Assert.Equal(TextAccuracyMetrics.Compare(expected, recognized), result.Compare(expected));
    }

    [Fact]
    public void The_result_overloads_treat_the_expected_text_as_the_reference()
    {
        // If the two were swapped, extra recognized text would show up as deletions instead of insertions
        // and the rate would be divided by the wrong length.
        var result = ResultWithText("abcd");

        var counts = result.Compare("abc").Characters;

        Assert.Equal(1, counts.Insertions);
        Assert.Equal(0, counts.Deletions);
        Assert.Equal(3, counts.ReferenceLength);
        Assert.Equal(1.0 / 3, result.CharacterErrorRate("abc"), 10);
    }

    [Fact]
    public void The_result_overloads_forward_the_comparison_options()
    {
        var result = ResultWithText("hello   world");

        Assert.NotEqual(0.0, result.CharacterErrorRate("Hello, World!"));
        Assert.Equal(0.0, result.CharacterErrorRate("Hello, World!", TextComparisonOptions.Relaxed), 10);
        Assert.Equal(0.0, result.WordErrorRate("Hello, World!", TextComparisonOptions.Relaxed), 10);
        Assert.Equal(0.0, result.Compare("Hello, World!", TextComparisonOptions.Relaxed).CharacterErrorRate, 10);
    }

    [Fact]
    public void The_result_overloads_score_the_full_text_and_not_the_individual_lines()
    {
        var result = new OcrResult
        {
            FullText = "line one\nline two",
            Lines = [new OcrLine { Text = "line one" }, new OcrLine { Text = "line two" }],
            Languages = ["en"],
        };

        Assert.Equal(0.0, result.CharacterErrorRate("line one\nline two"), 10);
        // The joining newline is a real character difference until whitespace collapsing is enabled.
        Assert.NotEqual(0.0, result.CharacterErrorRate("line one line two"));
        Assert.Equal(
            0.0,
            result.CharacterErrorRate("line one line two", new TextComparisonOptions { CollapseWhitespace = true }),
            10);
    }

    [Fact]
    public void An_empty_result_scores_one_against_any_expected_text_and_zero_against_none()
    {
        Assert.Equal(1.0, OcrResult.Empty.CharacterErrorRate("hello"), 10);
        Assert.Equal(1.0, OcrResult.Empty.WordErrorRate("hello"), 10);
        Assert.Equal(0.0, OcrResult.Empty.CharacterErrorRate(string.Empty), 10);
        Assert.Equal(ErrorCounts.Empty, OcrResult.Empty.Compare(string.Empty).Characters);
    }

    // ---------------------------------------------------------------- word tokenization

    [Fact]
    public void Leading_trailing_and_repeated_spaces_never_create_words()
    {
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate("the cat", "  the   cat  "), 10);
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate("  the cat  ", "the cat"), 10);
        Assert.Equal(new ErrorCounts(2, 0, 0, 0), TextAccuracyMetrics.Compare("the cat", " the  cat ").Words);
    }

    [Theory]
    [InlineData("one two three")]
    [InlineData("one\ttwo\tthree")]
    [InlineData("one\ntwo\nthree")]
    [InlineData("one\r\ntwo\r\nthree")]
    [InlineData("  one \t\t two \n three  ")]
    [InlineData("one two three")]
    public void Every_flavour_of_whitespace_delimits_words_the_same_way(string hypothesis)
    {
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate("one two three", hypothesis), 10);
        Assert.Equal(3, TextAccuracyMetrics.Compare("one two three", hypothesis).Words.Hits);
    }

    [Fact]
    public void Word_level_insertions_and_deletions_are_counted_per_token()
    {
        Assert.Equal(1.0 / 3, TextAccuracyMetrics.WordErrorRate("a b c", "a b x c"), 10);
        Assert.Equal(1.0 / 3, TextAccuracyMetrics.WordErrorRate("a b c", "a c"), 10);
        Assert.Equal(1.0 / 3, TextAccuracyMetrics.WordErrorRate("a b c", "a x c"), 10);
    }

    [Fact]
    public void A_mixed_word_alignment_reports_every_operation_it_used()
    {
        // "cat" became "dog" (substitution) and "down" was hallucinated (insertion).
        var words = TextAccuracyMetrics.Compare("the cat sat", "the dog sat down").Words;

        Assert.Equal(new ErrorCounts(2, 1, 1, 0), words);
        Assert.Equal(3, words.ReferenceLength);
        Assert.Equal(4, words.HypothesisLength);
        Assert.Equal(2.0 / 3, words.ErrorRate, 10);
    }

    [Fact]
    public void Word_metrics_are_case_and_punctuation_sensitive_until_told_otherwise()
    {
        // By default BOTH words differ — "Hello"/"hello" by case and "world"/"world!" by punctuation —
        // so that is two substitutions over a two-word reference: WER 1.0, not 0.5.
        Assert.Equal(1.0, TextAccuracyMetrics.WordErrorRate("Hello world", "hello world!"), 10);

        // Relaxed folds case and strips punctuation, so the same pair matches exactly.
        Assert.Equal(0.0, TextAccuracyMetrics.WordErrorRate("Hello world", "hello world!", TextComparisonOptions.Relaxed), 10);

        // And each option on its own repairs exactly one of the two words.
        Assert.Equal(0.5, TextAccuracyMetrics.WordErrorRate(
            "Hello world", "hello world!", new TextComparisonOptions { IgnoreCase = true }), 10);
        Assert.Equal(0.5, TextAccuracyMetrics.WordErrorRate(
            "Hello world", "hello world!", new TextComparisonOptions { StripPunctuation = true }), 10);
    }

    // ---------------------------------------------------------------- reference-implementation cross-check

    [Theory]
    [InlineData("", "", 0)]
    [InlineData("a", "", 1)]
    [InlineData("", "a", 1)]
    [InlineData("abc", "abc", 0)]
    [InlineData("kitten", "sitting", 3)]
    [InlineData("saturday", "sunday", 3)]
    [InlineData("flaw", "lawn", 2)]
    [InlineData("gumbo", "gambol", 2)]
    [InlineData("book", "back", 2)]
    [InlineData("abcdef", "abcdefgh", 2)]
    public void The_public_levenshtein_distance_matches_hand_checked_values(string a, string b, int expected)
    {
        Assert.Equal(expected, TextAccuracyMetrics.LevenshteinDistance(a, b));
        // Distance is symmetric when insertion and deletion cost the same.
        Assert.Equal(expected, TextAccuracyMetrics.LevenshteinDistance(b, a));
        Assert.Equal(expected, NaiveLevenshtein(a.ToCharArray(), b.ToCharArray()));
    }

    [Fact]
    public void The_rolling_row_alignment_agrees_with_a_naive_full_matrix_over_a_fixed_corpus()
    {
        var mismatches = new List<string>();

        foreach (var (reference, hypothesis) in DeterministicPairs())
        {
            int expected = NaiveLevenshtein(reference.ToCharArray(), hypothesis.ToCharArray());

            int distance = TextAccuracyMetrics.LevenshteinDistance(reference, hypothesis);
            if (distance != expected)
            {
                mismatches.Add($"LevenshteinDistance('{reference}','{hypothesis}') = {distance}, expected {expected}");
            }

            int characters = TextAccuracyMetrics
                .Compare(reference, hypothesis, Unit(CharacterUnit.Utf16CodeUnit))
                .Characters.TotalErrors;
            if (characters != expected)
            {
                mismatches.Add($"Compare('{reference}','{hypothesis}').Characters = {characters}, expected {expected}");
            }

            int words = TextAccuracyMetrics.Compare(reference, hypothesis).Words.TotalErrors;
            int expectedWords = NaiveLevenshtein(Tokens(reference), Tokens(hypothesis));
            if (words != expectedWords)
            {
                mismatches.Add($"Compare('{reference}','{hypothesis}').Words = {words}, expected {expectedWords}");
            }
        }

        Assert.Empty(mismatches);
    }

    [Fact]
    public void Every_character_unit_agrees_with_the_naive_matrix_over_the_fixed_corpus()
    {
        var mismatches = new List<string>();

        foreach (var (reference, hypothesis) in DeterministicPairs())
        {
            // The corpus is pure ASCII, so all three counting units must produce identical numbers.
            int expected = NaiveLevenshtein(reference.ToCharArray(), hypothesis.ToCharArray());

            foreach (var unit in Enum.GetValues<CharacterUnit>())
            {
                var counts = TextAccuracyMetrics.Compare(reference, hypothesis, Unit(unit)).Characters;
                if (counts.TotalErrors != expected)
                {
                    mismatches.Add($"{unit}: '{reference}' vs '{hypothesis}' = {counts.TotalErrors}, expected {expected}");
                }
                if (counts.ReferenceLength != reference.Length || counts.HypothesisLength != hypothesis.Length)
                {
                    mismatches.Add($"{unit}: '{reference}' vs '{hypothesis}' recovered lengths " +
                        $"{counts.ReferenceLength}/{counts.HypothesisLength}, expected {reference.Length}/{hypothesis.Length}");
                }
            }
        }

        Assert.Empty(mismatches);
    }

    [Fact]
    public void The_fixed_corpus_actually_exercises_both_orderings_and_non_trivial_edits()
    {
        // A guard on the guard: if the generator ever degenerated to identical or empty pairs, the
        // cross-check tests above would pass without proving anything.
        var pairs = DeterministicPairs();

        Assert.Equal(80, pairs.Count);
        Assert.Contains(pairs, p => p.Reference.Length > p.Hypothesis.Length);
        Assert.Contains(pairs, p => p.Reference.Length < p.Hypothesis.Length);
        Assert.Contains(pairs, p => p.Reference.Length > 0 && p.Hypothesis.Length > 0 && p.Reference != p.Hypothesis);
        Assert.Contains(pairs, p => Tokens(p.Reference).Length > 1);
    }
}
